import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { WixDesignSystemProvider, Box } from '@wix/design-system';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { fetchData } from '../redux/silces/calendarSlice';
import UserList from "@/components/users/userList";
import SplineChart from '../components/charts/splineChart/splineChart';
import UserTicketList from '../components/tickets/userTicketList';
import Header from '../components/header/header';
import "@wix/design-system/styles.global.css";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const dispatch = useDispatch<any>();
  
  useEffect(() => {
    dispatch(fetchData());
  }, []);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <WixDesignSystemProvider>
        <Box 
          direction="vertical" 
          maxWidth={'1368px'} 
          width={'100%'}
          gap="36px" 
          alignItems={'center'}
          padding={'0 10px'}
        >
          <Header />
          <UserTicketList />
          <SplineChart />
          <UserList />
        </Box>
      </WixDesignSystemProvider>
      </main>
    </>
  )
}